/**
 * Ecko Wallet Platform Theme
 * Supports both popup and offerLine styles
 */

export const light = {
    fontUrl: 'https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap',
    fontFamily: 'Montserrat',
    popupBg: '#1A1E3E',
    offerlinePopupBg: '#1A1E3E',
    offerlinePopupShadow: '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
    offerlinePlusIconColor: '#FFFFFF',
    offerlineLogoBg: 'transparent',
    logoBorderC: '#FFFFFF',
    logoBorderW: '1px',
    offerlineBtnHeight: '22px',
    offerlineBtnPadding: '7px 14px',
    offerlineBtnGap: '7.2px',
    offerlinePrimaryBtnWidth: '82px',
    offerlineSecondaryBtnWidth: '90px',
    xBtnFC: '#FFFFFF',
    closeFC: '#FFFFFF',
    offerlinePrimaryBtnBg: '#111111',
    offerlinePrimaryBtnFS: '11px',
    offerlinePrimaryBtnFW: '500',
    offerlinePrimaryBtnFC: '#FFF',
    offerlinePrimaryBtnBorderC: 'transparent',
    offerlinePrimaryBtnBorderW: '0',
    offerlinePrimaryBtnRadius: '6px',
    offerlineSecondaryBtnBg: '#EDEEF0',
    offerlineSecondaryBtnFS: '11px',
    offerlineSecondaryBtnFW: '500',
    offerlineSecondaryBtnFC: '#FFFFFF',
    offerlineSecondaryBtnBorderC: '#404A8D',
    offerlineSecondaryBtnBorderW: '2px',
    offerlineSecondaryBtnRadius: '100px',
    offerlineDetailsSubtitleFS: '17px',
    offerlineDetailsSubtitleFW: '400',
    offerlineDetailsSubtitleFC: '#FFFFFF',
    offerlineDetailsAmountFC: '#FFFFFF',
    offerlineDetailsAmountFW: '700',
    offerlineOptoutPauseFS: '17px',
    offerlineOptoutPauseFW: '400',
    offerlineOptoutPauseFC: '#FFFFFF',
    offerlineOptoutSuccessFC: '#FFFFFF',
    offerlineLoaderColor: '#FFF'
}

export const dark = {
    fontUrl: 'https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap',
    fontFamily: 'Montserrat',
    popupBg: '#1A1E3E',
    offerlinePopupBg: '#1A1E3E',
    offerlinePopupShadow: '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
    offerlinePlusIconColor: '#FFFFFF',
    logoBg: 'white',
    offerlineLogoBg: 'transparent',
    logoBorderC: '#FFFFFF',
    logoBorderW: '1px',
    offerlineBtnHeight: '22px',
    offerlineBtnPadding: '7px 14px',
    offerlineBtnGap: '6.057px',
    offerlinePrimaryBtnWidth: '82px',
    offerlineSecondaryBtnWidth: '90px',
    xBtnFC: '#FFFFFF',
    closeFC: '#FFFFFF',
    offerlinePrimaryBtnBg: '#404A8D',
    offerlinePrimaryBtnFS: '11px',
    offerlinePrimaryBtnFW: '500',
    offerlinePrimaryBtnFC: '#FFF',
    offerlinePrimaryBtnBorderC: 'transparent',
    offerlinePrimaryBtnBorderW: '0',
    offerlinePrimaryBtnRadius: '100px',
    offerlineSecondaryBtnBg: 'transparent',
    offerlineSecondaryBtnFS: '11px',
    offerlineSecondaryBtnFW: '500',
    offerlineSecondaryBtnFC: '#FFFFFF',
    offerlineSecondaryBtnBorderC: '#404A8D',
    offerlineSecondaryBtnBorderW: '2px',
    offerlineSecondaryBtnRadius: '100px',
    offerlineDetailsSubtitleFS: '17px',
    offerlineDetailsSubtitleFW: '400',
    offerlineDetailsSubtitleFC: '#FFFFFF',
    offerlineDetailsAmountFC: '#FFFFFF',
    offerlineDetailsAmountFW: '700',
    offerlineOptoutPauseFS: '17px',
    offerlineOptoutPauseFW: '400',
    offerlineOptoutPauseFC: '#FFFFFF',
    offerlineOptoutSuccessFC: '#FFFFFF',
    offerlineLoaderColor: '#FFF'
}
