/**
 * Platform-specific OfferLine styles
 * These styles are applied dynamically based on platformName from the server
 * This keeps the Extension simple - it doesn't need to know about platform-specific themes
 */

export interface PlatformStyles {
    [key: string]: string
}

export interface ThemeStyles {
    light: PlatformStyles
    dark: PlatformStyles
}

export interface PlatformThemes {
    [platformName: string]: ThemeStyles
}

/**
 * OfferLine platform-specific themes
 * Each platform can have different colors, fonts, etc.
 */
export const offerlinePlatformStyles: PlatformThemes = {
    yoroi: {
        light: {
            '--popup-bg': '#FFFFFF',
            '--offerline-popup-bg': '#FFFFFF',
            '--offerline-popup-shadow': '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
            '--offerline-plus-icon-color': '#FFFFFF',
            '--offerline-btn-height': '36px',
            '--offerline-btn-padding': '9.085px 20.189px',
            '--offerline-btn-gap': '6.057px',
            '--offerline-primary-btn-width': '120px',
            '--offerline-secondary-btn-width': '165px',
            '--x-btn-f-c': '#4B6DDE',
            '--close-f-c': '#4B6DDE',
            '--offerline-primary-btn-bg': '#4B6DDE',
            '--offerline-primary-btn-f-c': '#FFFFFF',
            '--offerline-primary-btn-f-w': '500',
            '--offerline-primary-btn-f-s': '15px',
            '--offerline-primary-btn-border-c': 'transparent',
            '--offerline-primary-btn-border-w': '0',
            '--offerline-primary-btn-radius': '8px',
            '--offerline-secondary-btn-bg': '#FFFFFF',
            '--offerline-secondary-btn-f-s': '15px',
            '--offerline-secondary-btn-f-w': '500',
            '--offerline-secondary-btn-f-c': '#4B6DDE',
            '--offerline-secondary-btn-border-c': '#4B6DDE',
            '--offerline-secondary-btn-border-w': '2px',
            '--offerline-secondary-btn-radius': '8px',
            '--offerline-details-subtitle-f-s': '17px',
            '--offerline-details-subtitle-f-w': '400',
            '--offerline-details-subtitle-f-c': '#1A1919',
            '--offerline-details-amount-f-c': '#1A1919',
            '--offerline-details-amount-f-w': '500',
            '--offerline-optout-success-f-c': '#FFFFFF',
        },
        dark: {
            '--popup-bg': '#3154CB',
            '--offerline-popup-bg': '#3154CB',
            '--offerline-popup-shadow': '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
            '--offerline-plus-icon-color': '#FFFFFF',
            '--offerline-btn-height': '36px',
            '--offerline-btn-padding': '9.085px 20.189px',
            '--offerline-btn-gap': '7.2px',
            '--offerline-primary-btn-width': '120px',
            '--offerline-secondary-btn-width': '165px',
            '--x-btn-f-c': '#FFFFFF',
            '--close-f-c': '#FFFFFF',
            '--offerline-primary-btn-bg': '#FFFFFF',
            '--offerline-primary-btn-f-s': '15px',
            '--offerline-primary-btn-f-w': '600',
            '--offerline-primary-btn-f-c': '#4B6DDE',
            '--offerline-primary-btn-border-c': 'transparent',
            '--offerline-primary-btn-border-w': '0',
            '--offerline-primary-btn-radius': '8px',
            '--offerline-secondary-btn-bg': 'transparent',
            '--offerline-secondary-btn-f-s': '15px',
            '--offerline-secondary-btn-f-w': '500',
            '--offerline-secondary-btn-f-c': '#FFFFFF',
            '--offerline-secondary-btn-border-c': '#FFFFFF',
            '--offerline-secondary-btn-border-w': '2px',
            '--offerline-secondary-btn-radius': '8px',
            '--offerline-details-subtitle-f-s': '17px',
            '--offerline-details-subtitle-f-w': '400',
            '--offerline-details-subtitle-f-c': '#FFFFFF',
            '--offerline-details-amount-f-c': '#FFFFFF',
            '--offerline-details-amount-f-w': '700',
            '--offerline-optout-pause-f-s': '18px',
            '--offerline-optout-pause-f-w': '400',
            '--offerline-optout-pause-f-c': '#FFFFFF',
            '--offerline-optout-success-f-c': '#FFFFFF'
        }
    },
    cspr: {
        light: {
            '--popup-bg': '#F5F6F7',
            '--offerline-popup-bg': '#F5F6F7',
            '--offerline-popup-shadow': '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
            '--offerline-plus-icon-color': '#B9BBBF',
            '--offerline-btn-height': '36px',
            '--offerline-btn-padding': '9.085px 20.189px',
            '--offerline-btn-gap': '6.057px',
            '--offerline-primary-btn-width': '120px',
            '--offerline-secondary-btn-width': '165px',
            '--x-btn-f-c': '#0A2EBF',
            '--close-f-c': '#0A2EBF',
            '--offerline-primary-btn-bg': '#CC000F',
            '--offerline-primary-btn-f-s': '15px',
            '--offerline-primary-btn-f-w': '600',
            '--offerline-primary-btn-f-c': '#FFF',
            '--offerline-primary-btn-border-c': 'transparent',
            '--offerline-primary-btn-border-w': '0',
            '--offerline-primary-btn-radius': '6px',
            '--offerline-secondary-btn-bg': '#EDEEF0',
            '--offerline-secondary-btn-f-s': '15px',
            '--offerline-secondary-btn-f-w': '400',
            '--offerline-secondary-btn-f-c': '#0A2EBF',
            '--offerline-secondary-btn-border-c': 'transparent',
            '--offerline-secondary-btn-border-w': '0px',
            '--offerline-secondary-btn-radius': '6px',
            '--offerline-details-subtitle-f-s': '17px',
            '--offerline-details-subtitle-f-w': '400',
            '--offerline-details-subtitle-f-c': '#1A1919',
            '--offerline-details-amount-f-c': '#1A1919',
            '--offerline-details-amount-f-w': '700',
            '--offerline-optout-pause-f-s': '17px',
            '--offerline-optout-pause-f-w': '400',
            '--offerline-optout-pause-f-c': '#1A1919',
            '--offerline-optout-success-f-c': '#1A1919',
        },
        dark: {
            '--popup-bg': '#F5F6F7',
            '--offerline-popup-bg': '#F5F6F7',
            '--offerline-popup-shadow': '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
            '--offerline-plus-icon-color': '#B9BBBF',
            '--offerline-btn-height': '36px',
            '--offerline-btn-padding': '9.085px 20.189px',
            '--offerline-btn-gap': '6.057px',
            '--offerline-primary-btn-width': '120px',
            '--offerline-secondary-btn-width': '165px',
            '--x-btn-f-c': '#0A2EBF',
            '--close-f-c': '#0A2EBF',
            '--offerline-primary-btn-bg': '#CC000F',
            '--offerline-primary-btn-f-s': '15px',
            '--offerline-primary-btn-f-w': '600',
            '--offerline-primary-btn-f-c': '#FFF',
            '--offerline-primary-btn-border-c': 'transparent',
            '--offerline-primary-btn-border-w': '0',
            '--offerline-primary-btn-radius': '6px',
            '--offerline-secondary-btn-bg': '#EDEEF0',
            '--offerline-secondary-btn-f-s': '15px',
            '--offerline-secondary-btn-f-w': '400',
            '--offerline-secondary-btn-f-c': '#0A2EBF',
            '--offerline-secondary-btn-border-c': 'transparent',
            '--offerline-secondary-btn-border-w': '0px',
            '--offerline-secondary-btn-radius': '6px',
            '--offerline-details-subtitle-f-s': '17px',
            '--offerline-details-subtitle-f-w': '400',
            '--offerline-details-subtitle-f-c': '#1A1919',
            '--offerline-details-amount-f-c': '#1A1919',
            '--offerline-details-amount-f-w': '700',
            '--offerline-optout-pause-f-s': '17px',
            '--offerline-optout-pause-f-w': '400',
            '--offerline-optout-pause-f-c': '#1A1919',
            '--offerline-optout-success-f-c': '#1A1919',
        }
    },
    ecko: {
        light: {
            '--popup-bg': '#1A1E3E',
            '--offerline-popup-bg': '#1A1E3E',
            '--offerline-popup-shadow': '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
            '--offerline-plus-icon-color': '#FFFFFF',
            '--offerline-btn-height': '36px',
            '--offerline-btn-padding': '9.085px 20.189px',
            '--offerline-btn-gap': '7.2px',
            '--offerline-primary-btn-width': '120px',
            '--offerline-secondary-btn-width': '165px',
            '--x-btn-f-c': '#FFFFFF',
            '--close-f-c': '#FFFFFF',
            '--offerline-primary-btn-bg': '#111111',
            '--offerline-primary-btn-f-s': '15px',
            '--offerline-primary-btn-f-w': '600',
            '--offerline-primary-btn-f-c': '#FFF',
            '--offerline-primary-btn-border-c': 'transparent',
            '--offerline-primary-btn-border-w': '0',
            '--offerline-primary-btn-radius': '6px',
            '--offerline-secondary-btn-bg': '#EDEEF0',
            '--offerline-secondary-btn-f-s': '15px',
            '--offerline-secondary-btn-f-w': '600',
            '--offerline-secondary-btn-f-c': '#FFFFFF',
            '--offerline-secondary-btn-border-c': '#404A8D',
            '--offerline-secondary-btn-border-w': '2px',
            '--offerline-secondary-btn-radius': '8px',
            '--offerline-details-subtitle-f-s': '17px',
            '--offerline-details-subtitle-f-w': '400',
            '--offerline-details-subtitle-f-c': '#1A1919',
            '--offerline-details-amount-f-c': '#1A1919',
            '--offerline-details-amount-f-w': '700',
            '--offerline-optout-pause-f-s': '18px',
            '--offerline-optout-pause-f-w': '400',
            '--offerline-optout-pause-f-c': '#FFFFFF',
            '--offerline-optout-success-f-c': '#FFFFFF',
        },
        dark: {
            '--popup-bg': '#1A1E3E',
            '--offerline-popup-bg': '#1A1E3E',
            '--offerline-popup-shadow': '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
            '--offerline-plus-icon-color': '#FFFFFF',
            '--offerline-btn-height': '36px',
            '--offerline-btn-padding': '9.085px 20.189px',
            '--offerline-btn-gap': '6.057px',
            '--offerline-primary-btn-width': '120px',
            '--offerline-secondary-btn-width': '165px',
            '--x-btn-f-c': '#FFFFFF',
            '--close-f-c': '#FFFFFF',
            '--offerline-primary-btn-bg': '#404A8D',
            '--offerline-primary-btn-f-s': '15px',
            '--offerline-primary-btn-f-w': '600',
            '--offerline-primary-btn-f-c': '#FFF',
            '--offerline-primary-btn-border-c': 'transparent',
            '--offerline-primary-btn-border-w': '0',
            '--offerline-primary-btn-radius': '100px',
            '--offerline-secondary-btn-bg': 'transparent',
            '--offerline-secondary-btn-f-s': '15px',
            '--offerline-secondary-btn-f-w': '600',
            '--offerline-secondary-btn-f-c': '#FFFFFF',
            '--offerline-secondary-btn-border-c': '#404A8D',
            '--offerline-secondary-btn-border-w': '2px',
            '--offerline-secondary-btn-radius': '8px',
            '--offerline-details-subtitle-f-s': '17px',
            '--offerline-details-subtitle-f-w': '400',
            '--offerline-details-subtitle-f-c': '#1A1919',
            '--offerline-details-amount-f-c': '#1A1919',
            '--offerline-details-amount-f-w': '700',
            '--offerline-optout-pause-f-s': '18px',
            '--offerline-optout-pause-f-w': '400',
            '--offerline-optout-pause-f-c': '#FFFFFF',
            '--offerline-optout-success-f-c': '#FFFFFF',
        }
    },
    fuel: {
        light: {
            '--popup-bg': '#000000',
            '--offerline-popup-bg': '#000000',
            '--offerline-popup-shadow': '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
            '--offerline-plus-icon-color': '#FFFFFF',
            '--offerline-btn-height': '36px',
            '--offerline-btn-padding': '9.085px 20.189px',
            '--offerline-btn-gap': '6.057px',
            '--offerline-primary-btn-width': '120px',
            '--offerline-secondary-btn-width': '165px',
            '--x-btn-f-c': '#FFFFFF',
            '--close-f-c': '#FFFFFF',
            '--offerline-primary-btn-bg': '#00DB7D',
            '--offerline-primary-btn-f-s': '15px',
            '--offerline-primary-btn-f-w': '500',
            '--offerline-primary-btn-f-c': '#000',
            '--offerline-primary-btn-border-c': 'transparent',
            '--offerline-primary-btn-border-w': '0',
            '--offerline-primary-btn-radius': '5.047px',
            '--offerline-secondary-btn-bg': 'transparent',
            '--offerline-secondary-btn-f-s': '15.142px',
            '--offerline-secondary-btn-f-w': '700',
            '--offerline-secondary-btn-f-c': '#00DB7D',
            '--offerline-secondary-btn-border-c': '#00DB7D',
            '--offerline-secondary-btn-border-w': '2px',
            '--offerline-secondary-btn-radius': '5.047px',
            '--offerline-details-subtitle-f-s': '17px',
            '--offerline-details-subtitle-f-w': '400',
            '--offerline-details-subtitle-f-c': '#1A1919',
            '--offerline-details-amount-f-c': '#1A1919',
            '--offerline-details-amount-f-w': '700',
            '--offerline-optout-pause-f-s': '19px',
            '--offerline-optout-pause-f-w': '400',
            '--offerline-optout-pause-f-c': '#FFFFFF',
        },
        dark: {
            '--popup-bg': '#000000',
            '--offerline-popup-bg': '#000000',
            '--offerline-popup-shadow': '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
            '--offerline-plus-icon-color': '#FFFFFF',
            '--offerline-btn-height': '36px',
            '--offerline-btn-padding': '9.085px 20.189px',
            '--offerline-btn-gap': '6.057px',
            '--offerline-primary-btn-width': '120px',
            '--offerline-secondary-btn-width': '165px',
            '--x-btn-f-c': '#FFFFFF',
            '--close-f-c': '#FFFFFF',
            '--offerline-primary-btn-bg': '#00DB7D',
            '--offerline-primary-btn-f-s': '15.142px',
            '--offerline-primary-btn-f-w': '700',
            '--offerline-primary-btn-f-c': '#000',
            '--offerline-primary-btn-border-c': 'transparent',
            '--offerline-primary-btn-border-w': '0',
            '--offerline-primary-btn-radius': '5.047px',
            '--offerline-secondary-btn-bg': 'transparent',
            '--offerline-secondary-btn-f-s': '15.142px',
            '--offerline-secondary-btn-f-w': '700',
            '--offerline-secondary-btn-f-c': '#00DB7D',
            '--offerline-secondary-btn-border-c': '#00DB7D',
            '--offerline-secondary-btn-border-w': '2px',
            '--offerline-secondary-btn-radius': '5.047px',
            '--offerline-details-subtitle-f-s': '17px',
            '--offerline-details-subtitle-f-w': '400',
            '--offerline-details-subtitle-f-c': '#FFFFFF',
            '--offerline-details-amount-f-c': '#FFFFFF',
            '--offerline-details-amount-f-w': '700',
            '--offerline-optout-pause-f-s': '18px',
            '--offerline-optout-pause-f-w': '400',
            '--offerline-optout-pause-f-c': '#FFFFFF',
            '--offerline-optout-success-f-c': '#FFFFFF',
        }
    }
}


/**
 * Apply platform-specific styles to the document
 */
export const applyPlatformStyles = (platformName: string, themeMode: 'light' | 'dark') => {
    const platform = platformName.toLowerCase()
    const styles = offerlinePlatformStyles[platform]?.[themeMode]

    if (!styles) {
        return
    }

    Object.entries(styles).forEach(([property, value]) => {
        document.documentElement.style.setProperty(property, value)
    })
}
